"use client";

import { ArrowRight, CalendarDays, Check, Menu, Shield, Users, X } from "lucide-react";
import { useState } from "react";

function Brand() {
  return <a className="marketing-logo" href="/" aria-label="NextSession Kids! Startseite"><span>NS</span><strong>NextSession<small>Kids!</small></strong></a>;
}

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="marketing-page">
    <header className="marketing-header"><Brand /><nav className={menuOpen ? "is-open" : ""}><a href="#funktionen" onClick={() => setMenuOpen(false)}>Funktionen</a><a href="#fuer-wen" onClick={() => setMenuOpen(false)}>Für wen</a><a href="#ablauf" onClick={() => setMenuOpen(false)}>So funktioniert&apos;s</a><a className="marketing-login-mobile" href="/login">Login</a></nav><div className="marketing-actions"><a className="marketing-primary small" href="/login">Zum Login <ArrowRight /></a></div><button className="marketing-menu-button" onClick={() => setMenuOpen((open) => !open)} aria-label="Menü öffnen">{menuOpen ? <X /> : <Menu />}</button></header>
    <section className="marketing-hero"><div className="marketing-hero-copy"><span className="marketing-eyebrow">FÜR FUSSBALLTRAINER, DIE MEHR WOLLEN.</span><h1>DEIN TEAM.<br />DEIN TRAINING.<br />DEINE PLANUNG.</h1><p>Vom ersten Hütchen bis zum Spieltag: Termine, Trainingsplanung und Kommunikation – alles für dein Team an einem Ort.</p><div className="marketing-hero-actions"><a className="marketing-primary" href="/login">Zum Login <ArrowRight /></a></div><div className="marketing-trust"><span><Check /> Für Trainer und Vereine</span><span><Check /> Web-App und iOS-ready</span></div></div><div className="marketing-hero-visual" aria-label="Vorschau der NextSession-Funktionen"><div className="dashboard-window"><div className="dashboard-bar"><i /><i /><i /><span>NextSession Kids!</span></div><div className="dashboard-content"><aside><strong>NS</strong><span className="active" /><span /><span /><span /></aside><div><div className="mock-welcome"><small>DEIN TRAINING</small><strong>Diese Woche im Plan</strong><div><b>3</b><span>Einheiten<br /><em>bereit für dein Team</em></span></div></div><div className="mock-cards"><article><CalendarDays /><small>NÄCHSTES TRAINING</small><strong>Ballgefühl & Dribbling</strong><span>Donnerstag · 17:00 Uhr</span></article><article><Users /><small>MANNSCHAFT</small><strong>14 Spieler</strong><span>12 Rückmeldungen offen</span></article></div></div></div></div><div className="marketing-float-card"><Shield /><span><small>ROLLEN & RECHTE</small><strong>Alles klar geregelt.</strong></span></div></div></section>
    <section className="marketing-feature-strip" id="funktionen"><article><span className="marketing-icon green"><CalendarDays /></span><div><strong>Trainingsplanung</strong><p>Übungen finden, Einheiten bauen und als Plan speichern.</p></div></article><article><span className="marketing-icon navy"><Users /></span><div><strong>Mannschaft organisieren</strong><p>Spieler, Trainer, Rollen und Rückmeldungen zentral verwalten.</p></div></article><article><span className="marketing-icon orange"><Shield /></span><div><strong>Bereit für den Spieltag</strong><p>Deine Daten bleiben in Web-App und späterer iOS-App synchron.</p></div></article></section>
    <section className="marketing-bottom" id="fuer-wen"><span className="marketing-eyebrow">EIN LOGIN. EIN GEMEINSAMER PLAN.</span><h2>Weniger Organisation.<br />Mehr Zeit fürs Team.</h2><p>NextSession bringt Mannschaft, Training und Termine in einen ruhigen, verständlichen Ablauf.</p><a className="marketing-secondary" href="/login">Zum Login <ArrowRight /></a></section>
    <footer className="marketing-footer"><span>© NextSession Kids!</span><a href="/login">Login</a></footer>
  </main>;
}
